name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ "main", "stable" ]
  merge_group:
    branches: [ "main", "stable" ]

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nox-tests:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            code:
              - "pdm.lock"
              - "**.py"
              - "tests/**"
      - name: Set up Python
        if: steps.changes.outputs.code == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox
        if: steps.changes.outputs.code == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Run tests
        if: steps.changes.outputs.code == 'true'
        run: |
          nox --session test
